# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskId', models.CharField(max_length=8)),
                ('Description', models.CharField(max_length=30)),
                ('DueDate', models.DateField()),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
