# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Text', models.CharField(max_length=140)),
                ('ConstructedYear', models.IntegerField()),
                ('Contractor', models.CharField(max_length=20)),
                ('Floor', models.CharField(max_length=4)),
                ('Shop', models.CharField(max_length=10)),
            ],
        ),
    ]
