# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='Contractor',
            new_name='Phone',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='ConstructedYear',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='Floor',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='Shop',
        ),
        migrations.AddField(
            model_name='memo',
            name='Email',
            field=models.CharField(default=None, max_length=140),
            preserve_default=False,
        ),
    ]
